import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/SessionProviders";
import NavigationBar from "@/components/nav-bar";
import { PresenceHeartbeat } from "@/components/PresenceHeartbeat";

const geist = Geist({
  variable: "--font-geist",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`dark ${geist.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Providers>
          <NavigationBar />
          <PresenceHeartbeat />
          {children}
        </Providers>
      </body>
    </html>
  );
}

